version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: jagatnewsdb
    ports:
      - '5499:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: